// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAampVsATjyqbq1GGQZEXsOJmTgdRJIAO8',
    appId: '1:1006163905368:web:7ad68fc085f474660d332d',
    messagingSenderId: '1006163905368',
    projectId: 'chat-app-5fc31',
    authDomain: 'chat-app-5fc31.firebaseapp.com',
    storageBucket: 'chat-app-5fc31.appspot.com',
    measurementId: 'G-ERGGWMMM9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3dqRqVJfaj9_qe5LGVwwnyukovI7sZ_M',
    appId: '1:1006163905368:android:8e4dd73a32fe21ad0d332d',
    messagingSenderId: '1006163905368',
    projectId: 'chat-app-5fc31',
    storageBucket: 'chat-app-5fc31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlLiTp8bRknURyvizXLepWiTvruJ0DA34',
    appId: '1:1006163905368:ios:c9eae89d222540b40d332d',
    messagingSenderId: '1006163905368',
    projectId: 'chat-app-5fc31',
    storageBucket: 'chat-app-5fc31.appspot.com',
    iosBundleId: 'com.example.graduatedProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlLiTp8bRknURyvizXLepWiTvruJ0DA34',
    appId: '1:1006163905368:ios:c9eae89d222540b40d332d',
    messagingSenderId: '1006163905368',
    projectId: 'chat-app-5fc31',
    storageBucket: 'chat-app-5fc31.appspot.com',
    iosBundleId: 'com.example.graduatedProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAampVsATjyqbq1GGQZEXsOJmTgdRJIAO8',
    appId: '1:1006163905368:web:37f61b374b58a18a0d332d',
    messagingSenderId: '1006163905368',
    projectId: 'chat-app-5fc31',
    authDomain: 'chat-app-5fc31.firebaseapp.com',
    storageBucket: 'chat-app-5fc31.appspot.com',
    measurementId: 'G-3G86RXR7S6',
  );
}
